### ISSUE TITLE
Basic Functionality

### ISSUE THREAD

**Issue by TheGor1lla** [BaranselKarakas/character-sheet-creator#1]
As a user I want to be able to visit the homepage of the app and be greeted by a stylized form that let's me enter basic information about my character:

* Name
* Profession
* A selection of stats

Once I entered the information into a form I want to be guided to a new page that shows all my entered information

**Comment by BaranselKarakas** [comment]
Resolved with merge:
https://github.com/BaranselKarakas/character-sheet-creator/pull/10
